services:
  WhiteDigital\EntityDtoMapper\Mapper\ClassMapper:
    autowire: true
  WhiteDigital\EntityDtoMapper\Mapper\EntityToResourceMapper:
    autowire: true
  WhiteDigital\EntityDtoMapper\Mapper\ResourceToEntityMapper:
    autowire: true
