services:
  WhiteDigital\EntityResourceMapper\Mapper\ClassMapper:
    autowire: true
  WhiteDigital\EntityResourceMapper\Mapper\EntityToResourceMapper:
    autowire: true
  WhiteDigital\EntityResourceMapper\Mapper\ResourceToEntityMapper:
    autowire: true
  WhiteDigital\EntityResourceMapper\Serializer\ArrayNormalizer:
    autowire: true
    autoconfigure: true
  WhiteDigital\EntityResourceMapper\Serializer\EntityNormalizer:
    autowire: true
    autoconfigure: true