services:
  WhiteDigital\EntityResourceMapper\Mapper\ClassMapper:
    autowire: true
  WhiteDigital\EntityResourceMapper\Mapper\EntityToResourceMapper:
    autowire: true
  WhiteDigital\EntityResourceMapper\Mapper\ResourceToEntityMapper:
    autowire: true
