services:
  WhiteDigital\EntityResourceMapper\Mapper\ClassMapper:
    autowire: true
    autoconfigure: true
  WhiteDigital\EntityResourceMapper\Mapper\EntityToResourceMapper:
    autowire: true
  WhiteDigital\EntityResourceMapper\Mapper\ResourceToEntityMapper:
    autowire: true
  WhiteDigital\EntityResourceMapper\Security\AuthorizationService:
    autowire: true
    autoconfigure: true
  WhiteDigital\EntityResourceMapper\Serializer\ArrayNormalizer:
    autowire: true
    autoconfigure: true
  WhiteDigital\EntityResourceMapper\Serializer\EntityNormalizer:
    autowire: true
    autoconfigure: true
  WhiteDigital\EntityResourceMapper\MenuBuilder\Service\MenuBuilderService:
    autowire: true
    autoconfigure: true
  WhiteDigital\EntityResourceMapper\Security\Interface\AccessResolverInterface:
    autowire: true
    autoconfigure: true
  WhiteDigital\EntityResourceMapper\Security\AccessResolver\OwnerPropertyAccessResolver:
    autowire: true
    autoconfigure: true