name: entity-resource-mapper-CI
on:
  [push, pull_request]
jobs:
  phpstan:
    runs-on: ubuntu-latest
    name: PHPStan
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
      - name: Checkout
        uses: actions/checkout@v4
      - name: composer install
        run: composer install
      - name: PHPStan
        run: composer phpstan
        env:
          REQUIRE_DEV: true
  tests:
    name: PHP ${{ matrix.php }} / SF ^${{ matrix.symfony }}
    runs-on: ubuntu-latest
    strategy:
        fail-fast: false
        matrix:
          include:
            - description: 'Symfony 7.1'
              php: '8.3'
              symfony: '7.1.*'
            - description: 'Symfony 7.1 on php 8.4'
              php: '8.4'
              symfony: '7.1.*'
            - description: 'Symfony 6.4'
              php: '8.3'
              symfony: '6.4.*'

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
      - run: |
          sed -ri 's/"symfony\/(.+)": "(.+)"/"symfony\/\1": "${{ matrix.symfony }}"/' composer.json;
      - run: composer update --no-interaction --no-progress --ansi
      - run: composer phpunit
